app:
  name: ui
  image:
    repository: 'onecx/onecx-help-ui'
  routing:
    enabled: true
    path: /mfe/help/
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      spec:
        exposedModule: "./OneCXHelpModule"
        description: "OneCX Help UI"
        note: "OneCX Help UI auto import via MF operator"
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          HELP:
            CREATE: Create help
            DELETE: Delete help
            EDIT: Edit help
            SAVE: Update and save help
            SEARCH: Search help
            VIEW: View mode for help
            EXPORT: Export help            
            IMPORT: Import help
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "onecx-help-ui"

# PIPE Config
